### ISSUE TITLE
10. Booking form layer

### ISSUE THREAD

**Issue by gallien** [jhyle/sapio#3]
http://clarberlin.com/sapio/10-buchung.html
http://clarberlin.com/sapio/10-buchung-daten.html
http://clarberlin.com/sapio/10-buchung-zusammen.html
http://clarberlin.com/sapio/10-buchung-bestaetigung.html

**Comment by pat-behrendt** [comment]
morgen wird alles  (von meinem wissensstand und dem material, von dem aus berechnet wurde) fertig sein (sofern alles kontrolliert und funktionsbereit .. einige sachen aber nicht komplett finalisiert,weil ich da änderungen vermute) .. kam am we beim treff mit ihm etwas raus/ soll ich auf etwas noch achten/ verbessern? 🎯
